### ISSUE TITLE
exception caught by widgets library on CardSettingsDateTimePicker()

### ISSUE THREAD

**Issue by robertoltrocha** [codegrue/card_settings#136]
Hi, when I am using the CardSettingsDateTimePicker() I have "exception caught by widgets library".
I am using android, device - Sansumg S-10 plus
card_settings: ^1.13.0+hotfix.1
With anothers CardSettings(text, int, paragraph, Date) I do not have this issue.

```
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [versÃ£o 10.0.19041.508], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] VS Code, 64-bit edition (version 1.49.0)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)
```

```
  CardSettingsDateTimePicker(
                        showMaterialonIOS: true,
                        initialValue: devProd.data_ocorrencia,
                        label: "Criado:",
                        requiredIndicator: Text("*", style: TextStyle(color: Colors.red),),
                        enabled: editMode,
                        onChanged: (value) {
                          devProd.data_ocorrencia = value;
                        },
                        onSaved: (value) {
                          devProd.data_ocorrencia = value;
                        },
                      ),
```

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.
The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a
RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.
Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically,
Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a _Decorator widget.
The ownership chain for the RenderObject that received the incompatible parent data was:
  RichText ← Text ← Flexible ← _Decorator ← InputDecorator ← Expanded ← Row ← Column ← Padding ←
Container ← ⋯

When the exception was thrown, this was the stack:
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5726:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5420:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5987:11)
...     Normal element mounting (13 frames)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#19     _RenderDecorationElement._mountChild (package:flutter/src/material/input_decorator.dart:1561:30)
#20     _RenderDecorationElement.mount (package:flutter/src/material/input_decorator.dart:1576:5)
...     Normal element mounting (15 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#36     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (50 frames)
#88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#89     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (76 frames)
#165    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#166    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
...     Normal element mounting (140 frames)
#306    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#307    Element.updateChild (package:flutter/src/widgets/framework.dart:3255:20)
#308    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#309    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#310    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#311    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#312    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#313    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#314    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#315    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#316    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#317    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#318    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#319    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#320    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5566:32)
#321    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6001:17)
#322    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#323    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#324    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#325    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#326    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#327    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#328    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#329    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#330    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#331    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#332    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#333    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#334    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#335    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#336    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#337    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#338    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#339    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#340    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#341    StatelessElement.update (package:flutter/src/widgets/framework.dart:4627:5)
#342    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#343    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5881:14)
#344    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#345    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#346    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#347    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#348    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#349    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#350    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#351    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#352    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#353    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#354    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#355    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#356    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#357    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#358    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#359    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#360    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#361    ProxyElement.update (package:flutter/src/widgets/framework.dart:4906:5)
#362    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#363    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#364    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#365    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#366    StatefulElement.update (package:flutter/src/widgets/framework.dart:4751:5)
#367    Element.updateChild (package:flutter/src/widgets/framework.dart:3245:15)
#368    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#369    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#370    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#371    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:33)
#372    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:866:20)
#373    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#374    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#375    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#376    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#380    _invoke (dart:ui/hooks.dart:253:10)
#381    _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Flexible(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Flexible widget has the wrong ancestor RenderObjectWidget. Typically, Flexible widgets are placed directly inside Flex widgets.
The offending Flexible is currently placed inside a _Decorator widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  RichText ← Text ← Flexible ← _Decorator ← InputDecorator ← Expanded ← Row ← Column ← Padding ← Container ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5689:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5705:6)
#2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5726:7)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5420:5)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5987:11)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
D/SmartClipDataCropperImpl( 3965): doExtractSmartClipData : Extraction start! reqId = 457  Cropped area = Rect(540, 1140 - 541, 1141)  Package = 
D/SmartClipDataCropperImpl( 3965): addAppMetaTag :
D/SmartClipDataCropperImpl( 3965): sendExtractionResultToSmartClipService : -- Extracted SmartClip data information --
D/SmartClipDataCropperImpl( 3965): sendExtractionResultToSmartClipService : Request Id : 457
D/SmartClipDataCropperImpl( 3965): sendExtractionResultToSmartClipService : Extraction mode : 1
D/SemSmartClipDataRepository( 3965): ----- Start of SmartClip repository informations -----
D/SemSmartClipDataRepository( 3965): ** Content type : image
D/SemSmartClipDataRepository( 3965): ** Meta area rect : Rect(0, 0 - 0, 0)
D/SemSmartClipDataRepository( 3965): ** Captured image file path : null
D/SemSmartClipDataRepository( 3965): ----- End of SmartClip repository informations -----
D/SmartClipDataCropperImpl( 3965): sendExtractionResultToSmartClipService : Elapsed = 8
D/SmartClipRemoteRequestDispatcher( 3965): dispatchScrollableAreaInfo : windowRect = Rect(0, 0 - 1080, 2280)
D/SmartClipRemoteRequestDispatcher( 3965): dispatchScrollableAreaInfo : Scrollable view count = 1
D/SmartClipRemoteRequestDispatcher( 3965): dispatchScrollableAreaInfo : Unscrollable view count = 0
D/SmartClipRemoteRequestDispatcher( 3965): dispatchScrollableAreaInfo : Pkg=br.com.bobsystem.sii Activity=null
I/ViewRootImpl@5c7e46d[MainActivity]( 3965): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 3965): prepareNavigationBarInfo() DecorView@51bedbb[MainActivity]
D/InputMethodManager( 3965): getNavigationBarColor() -855310
D/InputTransport( 3965): Input channel destroyed: 'ClientS', fd=96
I/SurfaceView( 3965): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{93c5933 V.E...... ........ 0,0-1080,2241} of ViewRootImpl@5c7e46d[MainActivity]
I/SurfaceView( 3965): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{93c5933 V.E...... ........ 0,0-1080,2241}
I/mali_egl( 3965): eglDestroySurface() in
I/mali_winsys( 3965): delete_surface() [1080x2241] return
I/mali_egl( 3965): eglDestroySurface() out
W/libEGL  ( 3965): EGLNativeWindowType 0x73d1fa4010 disconnect failed
I/SurfaceView( 3965): remove() io.flutter.embedding.android.FlutterSurfaceView{93c5933 V.E...... ........ 0,0-1080,2241} Surface(name=SurfaceView - br.
D/OpenGLRenderer( 3965): makeCurrent EglSurface : 0x742e809700 -> 0x0
D/OpenGLRenderer( 3965): destroyEglSurface : 0x742e809700
I/mali_egl( 3965): eglDestroySurface() in
I/mali_winsys( 3965): delete_surface() [1080x2280] return
I/mali_egl( 3965): eglDestroySurface() out
E/OpenGLRenderer( 3965): ReliableSurface: perform returned an error
W/libEGL  ( 3965): EGLNativeWindowType 0x742e81c1d0 disconnect failed
D/OpenGLRenderer( 3965): ~ReliableSurface : 0x742e81c1c0
I/ViewRootImpl@5c7e46d[MainActivity]( 3965): Relayout returned: old=(0,0,1080,2280) new=(0,0,1080,2280) req=(1080,2280)8 dur=16 res=0x5 s={false 0} ch=true
I/ViewRootImpl@5c7e46d[MainActivity]( 3965): stopped(true) old=false
I/SurfaceView( 3965): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{93c5933 V.E...... ........ 0,0-1080,2241} of ViewRootImpl@5c7e46d[MainActivity]
```

![WhatsApp Image 2020-09-24 at 21 07 35](https://user-images.githubusercontent.com/30963205/94212635-11d11800-feab-11ea-8ba6-1eeb2c713235.jpeg)

**Comment by codegrue** [comment]
Fixed in version 1.13.0
