### ISSUE TITLE
the getter 'color' was called on null.

### ISSUE THREAD

**Issue by ahmedkassem** [codegrue/card_settings#35]
this error appears in Date Picker and Time Picker, even when running the example

![screenshot_1](https://user-images.githubusercontent.com/7607004/47928141-026b0f00-dece-11e8-86d2-ab93b94c3fed.png)

**Comment by codegrue** [comment]
I just built the project, ran it on an iphone XR, and no error with the pickers in the example. Can you run in debug to see what line is causing your error?

**Comment by ahmedkassem** [comment]
sorry, i tried again the example and it is working fine, the problem is with my implementation:
where the state is:
  DateTime showDateTime = DateTime(2010, 10, 10, 20, 30);

and the code for date picker is:
                CardSettingsDatePicker(
                  icon: Icon(Icons.calendar_today),
                  label: 'Date',
                  initialValue: showDateTime,
                  onSaved: (value) =>
                      showDateTime = updateJustDate(value, showDateTime),
                ),

when using this i get this error:
I/flutter ( 3898): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3898): The following NoSuchMethodError was thrown building CardSettingsField(dirty):
I/flutter ( 3898): The getter 'color' was called on null.
I/flutter ( 3898): Receiver: null
I/flutter ( 3898): Tried calling: color
I/flutter ( 3898):
I/flutter ( 3898): When the exception was thrown, this was the stack:
I/flutter ( 3898): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 3898): #1      CardSettingsField._buildLeftIcon (package:card_settings/widgets/card_settings_field.dart:167:72)
I/flutter ( 3898): #2      CardSettingsField._buildLabelRow (package:card_settings/widgets/card_settings_field.dart:99:11)
I/flutter ( 3898): #3      CardSettingsField.build (package:card_settings/widgets/card_settings_field.dart:52:21)
I/flutter ( 3898): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:3731:28)
I/flutter ( 3898): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3678:15)

**Comment by codegrue** [comment]
Okay it's in the _buildLeftIcon method which has this line:

color: Theme.of(context).inputDecorationTheme.labelStyle.color,

so that theme property must be coming over as null for some reason in your project. 

I will submit a fix momentarily.
